// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: amisdemo.proto

package pb_gen

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AmisDemoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *AmisDemoRequest) Reset() {
	*x = AmisDemoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amisdemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmisDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmisDemoRequest) ProtoMessage() {}

func (x *AmisDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amisdemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmisDemoRequest.ProtoReflect.Descriptor instead.
func (*AmisDemoRequest) Descriptor() ([]byte, []int) {
	return file_amisdemo_proto_rawDescGZIP(), []int{0}
}

func (x *AmisDemoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AmisDemoRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type AmisDemoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Tips   string `protobuf:"bytes,2,opt,name=tips,proto3" json:"tips,omitempty"`
}

func (x *AmisDemoResponse) Reset() {
	*x = AmisDemoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amisdemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmisDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmisDemoResponse) ProtoMessage() {}

func (x *AmisDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amisdemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmisDemoResponse.ProtoReflect.Descriptor instead.
func (*AmisDemoResponse) Descriptor() ([]byte, []int) {
	return file_amisdemo_proto_rawDescGZIP(), []int{1}
}

func (x *AmisDemoResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AmisDemoResponse) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

var File_amisdemo_proto protoreflect.FileDescriptor

var file_amisdemo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6d, 0x69, 0x73, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x22, 0x37, 0x0a, 0x0f, 0x41, 0x6d, 0x69, 0x73,
	0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x22, 0x3e, 0x0a, 0x10, 0x41, 0x6d, 0x69, 0x73, 0x44, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_amisdemo_proto_rawDescOnce sync.Once
	file_amisdemo_proto_rawDescData = file_amisdemo_proto_rawDesc
)

func file_amisdemo_proto_rawDescGZIP() []byte {
	file_amisdemo_proto_rawDescOnce.Do(func() {
		file_amisdemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_amisdemo_proto_rawDescData)
	})
	return file_amisdemo_proto_rawDescData
}

var file_amisdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_amisdemo_proto_goTypes = []interface{}{
	(*AmisDemoRequest)(nil),  // 0: pb_gen.AmisDemoRequest
	(*AmisDemoResponse)(nil), // 1: pb_gen.AmisDemoResponse
}
var file_amisdemo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amisdemo_proto_init() }
func file_amisdemo_proto_init() {
	if File_amisdemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_amisdemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AmisDemoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amisdemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AmisDemoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_amisdemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amisdemo_proto_goTypes,
		DependencyIndexes: file_amisdemo_proto_depIdxs,
		MessageInfos:      file_amisdemo_proto_msgTypes,
	}.Build()
	File_amisdemo_proto = out.File
	file_amisdemo_proto_rawDesc = nil
	file_amisdemo_proto_goTypes = nil
	file_amisdemo_proto_depIdxs = nil
}
