// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: error.proto

package pb_gen

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ErrNo int32

const (
	ErrNo_UnknoweErr                 ErrNo = 0
	ErrNo_Success                    ErrNo = 1
	ErrNo_Internal_Err               ErrNo = 99  //服务器内部错误
	ErrNo_Email_ForMat_Error         ErrNo = 100 //邮件格式错误
	ErrNo_User_Already_Exist         ErrNo = 101 //已经存在这个用户
	ErrNo_Cache_No_Verification_code ErrNo = 102 //缓存中没有这个验证码
	ErrNo_Verification_Code_Error    ErrNo = 103 //验证码错误
	ErrNo_Password_Not_Same          ErrNo = 104 //两次密码不同
	ErrNo_User_Not_Exist             ErrNo = 105 //用户不存在
	ErrNo_Login_Password_Error       ErrNo = 106 //密码错误
)

// Enum value maps for ErrNo.
var (
	ErrNo_name = map[int32]string{
		0:   "UnknoweErr",
		1:   "Success",
		99:  "Internal_Err",
		100: "Email_ForMat_Error",
		101: "User_Already_Exist",
		102: "Cache_No_Verification_code",
		103: "Verification_Code_Error",
		104: "Password_Not_Same",
		105: "User_Not_Exist",
		106: "Login_Password_Error",
	}
	ErrNo_value = map[string]int32{
		"UnknoweErr":                 0,
		"Success":                    1,
		"Internal_Err":               99,
		"Email_ForMat_Error":         100,
		"User_Already_Exist":         101,
		"Cache_No_Verification_code": 102,
		"Verification_Code_Error":    103,
		"Password_Not_Same":          104,
		"User_Not_Exist":             105,
		"Login_Password_Error":       106,
	}
)

func (x ErrNo) Enum() *ErrNo {
	p := new(ErrNo)
	*p = x
	return p
}

func (x ErrNo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrNo) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (ErrNo) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x ErrNo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrNo.Descriptor instead.
func (ErrNo) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

var File_error_proto protoreflect.FileDescriptor

var file_error_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x62, 0x5f, 0x67, 0x65, 0x6e, 0x2a, 0xe8, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x4e, 0x6f, 0x12,
	0x0e, 0x0a, 0x0a, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x65, 0x45, 0x72, 0x72, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x45, 0x72, 0x72, 0x10, 0x63, 0x12, 0x16,
	0x0a, 0x12, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x74, 0x5f, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x64, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x41,
	0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x65, 0x12, 0x1e,
	0x0a, 0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x4e, 0x6f, 0x5f, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x10, 0x66, 0x12, 0x1b,
	0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x43,
	0x6f, 0x64, 0x65, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x67, 0x12, 0x15, 0x0a, 0x11, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x4e, 0x6f, 0x74, 0x5f, 0x53, 0x61, 0x6d, 0x65,
	0x10, 0x68, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x4e, 0x6f, 0x74, 0x5f, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x10, 0x69, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x6a,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData = file_error_proto_rawDesc
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_error_proto_rawDescData)
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_proto_goTypes = []interface{}{
	(ErrNo)(0), // 0: pb_gen.ErrNo
}
var file_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_rawDesc = nil
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
