// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: room_info.proto

package pb_gen

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoomStatus int32

const (
	RoomStatus_Unknow    RoomStatus = 0
	RoomStatus_Creating  RoomStatus = 1 //创建
	RoomStatus_Reviewing RoomStatus = 2 //审核
	RoomStatus_Usering   RoomStatus = 3 //审核
	RoomStatus_Closing   RoomStatus = 4 //关闭
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "Unknow",
		1: "Creating",
		2: "Reviewing",
		3: "Usering",
		4: "Closing",
	}
	RoomStatus_value = map[string]int32{
		"Unknow":    0,
		"Creating":  1,
		"Reviewing": 2,
		"Usering":   3,
		"Closing":   4,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_info_proto_enumTypes[0].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_room_info_proto_enumTypes[0]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_info_proto_rawDescGZIP(), []int{0}
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId         int64      `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TeacherId      int64      `protobuf:"varint,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`                           //教室所属的teacher
	StudentCnt     int64      `protobuf:"varint,3,opt,name=student_cnt,json=studentCnt,proto3" json:"student_cnt,omitempty"`                        //教室的学生数量
	RoomReviewerId int64      `protobuf:"varint,4,opt,name=room_reviewer_id,json=roomReviewerId,proto3" json:"room_reviewer_id,omitempty"`          //教室审核人的id 特指管理员
	RoomName       string     `protobuf:"bytes,5,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`                               //教室的名字
	RoomStatus     RoomStatus `protobuf:"varint,6,opt,name=room_status,json=roomStatus,proto3,enum=pb_gen.RoomStatus" json:"room_status,omitempty"` //教室的状态
	RoomCapcity    int64      `protobuf:"varint,7,opt,name=RoomCapcity,proto3" json:"RoomCapcity,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_room_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_room_info_proto_rawDescGZIP(), []int{0}
}

func (x *RoomInfo) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *RoomInfo) GetStudentCnt() int64 {
	if x != nil {
		return x.StudentCnt
	}
	return 0
}

func (x *RoomInfo) GetRoomReviewerId() int64 {
	if x != nil {
		return x.RoomReviewerId
	}
	return 0
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetRoomStatus() RoomStatus {
	if x != nil {
		return x.RoomStatus
	}
	return RoomStatus_Unknow
}

func (x *RoomInfo) GetRoomCapcity() int64 {
	if x != nil {
		return x.RoomCapcity
	}
	return 0
}

var File_room_info_proto protoreflect.FileDescriptor

var file_room_info_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x22, 0x81, 0x02, 0x0a, 0x08, 0x52, 0x6f,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x6e, 0x74, 0x12,
	0x28, 0x0a, 0x10, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f,
	0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62,
	0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x70, 0x63, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x70, 0x63, 0x69, 0x74, 0x79, 0x2a, 0x4f, 0x0a,
	0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x69,
	0x6e, 0x67, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6c, 0x6f, 0x73, 0x69, 0x6e, 0x67, 0x10, 0x04, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_info_proto_rawDescOnce sync.Once
	file_room_info_proto_rawDescData = file_room_info_proto_rawDesc
)

func file_room_info_proto_rawDescGZIP() []byte {
	file_room_info_proto_rawDescOnce.Do(func() {
		file_room_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_info_proto_rawDescData)
	})
	return file_room_info_proto_rawDescData
}

var file_room_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_room_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_room_info_proto_goTypes = []interface{}{
	(RoomStatus)(0),  // 0: pb_gen.RoomStatus
	(*RoomInfo)(nil), // 1: pb_gen.RoomInfo
}
var file_room_info_proto_depIdxs = []int32{
	0, // 0: pb_gen.RoomInfo.room_status:type_name -> pb_gen.RoomStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_room_info_proto_init() }
func file_room_info_proto_init() {
	if File_room_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_info_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_room_info_proto_goTypes,
		DependencyIndexes: file_room_info_proto_depIdxs,
		EnumInfos:         file_room_info_proto_enumTypes,
		MessageInfos:      file_room_info_proto_msgTypes,
	}.Build()
	File_room_info_proto = out.File
	file_room_info_proto_rawDesc = nil
	file_room_info_proto_goTypes = nil
	file_room_info_proto_depIdxs = nil
}
